project:
  type: website

website:
  title: "Victorian public library story"
  navbar:
    left:
      - href: index.qmd
        text: Story

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
