project:
  type: website
  render:
    - "*.qmd"
    - "!*-supp.qmd"
    - "*.md"
  resources:
    - "*-supp.qmd"
    - "assignments/assignment-2-papers/*.pdf"
    - "week10/tutorial/solar_data.csv"

website:
  title: "ETC5523 Communicating With Data"
  site-url: "https://cwd.numbat.space"
  navbar:
    background: "#006dae"
    left:
      - href: index.qmd
        text: Home
        icon: house-fill
      - text: Discussion
        icon: chat-fill
        href: "https://learning.monash.edu/mod/forum/view.php?id=111111"
      - text: Moodle
        icon: mortarboard-fill
        href: "https://learning.monash.edu/course/view.php?id=22222&section=1"
    right:
      - icon: github
        href: https://github.com/numbats/cwd

date-format: "D MMMM YYYY"

format:
  html:
    theme: [cosmo, numbat.scss]
    highlight: textmate
    toc: true
    mainfont: "Fira Sans"
    html-math-method: katex
    include-in-header:
      file: header.html

execute:
  echo: false
  warning: false
  message: false

engine: knitr
