---
pagetitle: "What's happening with the Australian labor market?"
author: "Michael Lydeamore"
footer: "ETC5523 Tutorial 3A Example Answer"
format: 
  revealjs:
    slide-number: true
    show-slide-number: all
    width: 1280
    height: 720
execute:
  echo: false
---

# [`r rmarkdown::metadata$pagetitle`]{style="color:white;"} {#title-slide background-color="rgb(255, 99, 71)" }

[`r rmarkdown::metadata$author`]{style="color:white;"}


```{r setup}
library(tidyverse)
library(readabs)
theme_set(theme_bw(base_size = 18) + 
            theme(plot.caption = element_text(hjust = 0, 
                                              size = 12,
                                              color = "grey60")))
knitr::opts_chunk$set(dev = "svg")
```

```{r data, cache = TRUE}
youth_unemploy <- read_abs(series_id = "A84591889X") #> 15-24 years ;  Unemployment rate ;  Persons ;
unemploy <- read_abs(series_id = "A84591917W")
fulltime_earnings <- read_abs(series_id = "A85002151A")
CPI <- read_abs(series_id = "A2325846C") # Index Numbers ;  All groups CPI ;  Australia ;
WPI <- read_abs(series_id = "A2603609J") # Quarterly Index ;  Total hourly rates of pay excluding bonuses ;  Australia ;  Private ;  All industries ;
```


## Unemployment is an all time low!




```{r}
youth_unemploy %>% 
  select(date, value) %>% 
  mutate(type = "Youth\n(16-24 years old)") %>% 
  bind_rows(select(unemploy, date, value) %>% 
              mutate(type = "All")) %>% 
  ggplot(aes(date, value, color = type)) +
  geom_hline(data = ~filter(.x, date==max(date)),
             aes(yintercept = value, alpha = type),
             color = "tomato1",
             linetype = "dashed") +
  geom_line() +
  geom_text(data = ~filter(.x, date==as.Date("2015-01-01")),
            aes(label = type), size = 7, nudge_y = 2) +
  geom_point(data = ~filter(.x, date==max(date)), 
             color = "tomato1", size = 1, 
             aes(alpha = type)) +
  ggrepel::geom_text_repel(data = ~filter(.x, date==max(date)), 
                           color = "tomato1",
                           aes(label = scales::percent(value/100, 0.1),
                               alpha = type), 
                           nudge_x = 1, nudge_y = 1, hjust = 0) +
  labs(x = "", y = "Unemployment rate (%)",
       caption = str_wrap("Data source: Australian Bureau of Statistics (July 2022) 'Table 1. Labour force status by Age, Social marital status, and Sex' [time series spreadsheet], Labour Force, Australia, Detailed, https://www.abs.gov.au/statistics/labour/employment-and-unemployment/labour-force-australia-detailed/jul-2022 accessed 4 September 2022.")) +
  guides(color = "none", alpha = "none") +
  scale_color_manual(values = c("grey50", "grey80")) +
  scale_alpha_manual(values = c(0.8, 0.5))
```


## But wages aren't growing fast enough!

```{r}
CPI %>% 
  select(date, cpi = value) %>% 
  left_join(select(WPI, date, wpi = value), by = "date") %>% 
  filter(!is.na(wpi)) %>% 
  ggplot(aes(date, (wpi - cpi)/cpi)) + 
  geom_line(color = "grey60") +
  geom_line(data = ~filter(.x, date >= as.Date("2020-04-01")),
            color = "tomato1") +
  scale_y_continuous(labels = scales::percent) +
  labs(x = "", y = "(WPI - CPI) / CPI",
       caption = str_wrap("Data source: Australian Bureau of Statistics (June 2022) 'Table 1 and 2. CPI: All Groups, Index Numbers and Percentage Changes' and 'Table 1. Total Hourly Rates of Pay Excluding Bonuses: Sector, Original, Seasonally Adjusted and Trend' [time series spreadsheet], Consumer Price Index, Australia, https://www.abs.gov.au/statistics/economy/price-indexes-and-inflation/consumer-price-index-australia/jun-2022, Wage Price Index, Australia,https://www.abs.gov.au/statistics/economy/price-indexes-and-inflation/wage-price-index-australia/jun-2022 accessed 4 September 2022.", width = 120))
```


## Wage growth isn't like what it used to be

```{r}
fulltime_earnings %>% 
  # data is collected biannually in May and Nov so make sure to 
  # compare May to May, Nov to Nov
  arrange(date) %>% 
  mutate(perc = slider::slide_dbl(value, ~(.x[3] - .x[1]) / .x[1], 
                                  .before = 2, .step = 1),
         perc_lag1 = slider::slide_dbl(perc, ~.x[2], .after = 1, .step = 1)) %>% 
  ggplot(aes(date, perc, 
             color = perc_lag1 < 0.03, group = 1)) + 
  geom_line() +
  labs(x = "", y = "", title = str_wrap("Percentage increase of average weekly earnings compared to the same period from the previous year", 60),
       caption = str_wrap("Data source: Australian Bureau of Statistics (May 2022)  'Table 3. Average Weekly Earnings, Australia (Dollars) - Original' [time series spreadsheet], Average Weekly Earnings, Australia, https://www.abs.gov.au/statistics/labour/earnings-and-working-conditions/average-weekly-earnings-australia/may-2022 accessed 4 September 2022.", width = 120)) +
  scale_y_continuous(labels = scales::percent) +
  guides(color = "none") +
  scale_color_manual(values = c("black", "tomato1"))
```



## {background-color="rgb(255, 99, 71)"}

<br><br>

<center style="font-size:3em; color: white; font-weight:bold;">

Real wages need to increase!

</center>

. . . 

<center>
[Inspired from the report by Peter Hannam, "Australia’s jobless rate is only 3.4% – so what’s holding wage growth back?" at The Guardian ](https://www.theguardian.com/business/2022/aug/18/australias-jobless-rate-is-only-34-so-whats-holding-wage-growth-back)
</center>

```{css, echo = FALSE}
a {
  color: #e3e3e3!important;
}
```

